EIDAS_TOMCAT_DIR=~/eidas-tomcat

STUB_SP_HTTP_PORT=56000
CONNECTOR_NODE_HTTP_PORT=$((STUB_SP_HTTP_PORT + 1))
NL_PROXY_NODE_HTTP_PORT=$((STUB_SP_HTTP_PORT + 2))
FR_PROXY_NODE_HTTP_PORT=$((STUB_SP_HTTP_PORT + 3))
NL_STUB_IDP_HTTP_PORT=$((STUB_SP_HTTP_PORT + 4))
FR_STUB_IDP_HTTP_PORT=$((STUB_SP_HTTP_PORT + 5))
