EIDAS_TOMCAT_DIR=~/eidas-tomcat

STUB_SP_HTTP_PORT=56000
CONNECTOR_NODE_HTTP_PORT=$((STUB_SP_HTTP_PORT + 1))
COUNTRY_1_PROXY_NODE_HTTP_PORT=$((STUB_SP_HTTP_PORT + 2))
COUNTRY_2_PROXY_NODE_HTTP_PORT=$((STUB_SP_HTTP_PORT + 3))
COUNTRY_1_STUB_IDP_HTTP_PORT=$((STUB_SP_HTTP_PORT + 4))
COUNTRY_2_STUB_IDP_HTTP_PORT=$((STUB_SP_HTTP_PORT + 5))
