EIDAS_TOMCAT_DIR=~/eidas-tomcat

STUB_SP_HTTP_PORT=56000
CONNECTOR_NODE_HTTP_PORT=$((STUB_SP_HTTP_PORT + 1))
PROXY_NODE_HTTP_PORT=$((STUB_SP_HTTP_PORT + 2))
STUB_IDP_HTTP_PORT=$((STUB_SP_HTTP_PORT + 3))
